import Head from "next/head";
import Layout, { siteTitle } from "../components/Layout";
import { File } from "./api/getFiles";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import { useEffect, useState, useRef } from "react";
import Button from "../components/Button";
import DownIcon from "../public/chevronDown.svg";
import PlusIcon from "../public/plusIcon.svg";
import DownloadIcon from "../public/downloadIcon.svg";
import TrashIcon from "../public/trashIcon.svg";
import SelectedCard from "../components/SelectedCard";
import DownloadButton from "../components/DownloadButton";
import axios from "axios";

const Home = () => {
  const [search, setSearch] = useState<string[]>([]);
  const [selectedCard, setSelectedCard] = useState<string[]>([]);
  const [selectedMode, setSelectedMode] = useState<boolean>(false);
  const [files, setFiles] = useState<File[]>([]);

  const inputFile = useRef(null);

  // fetching files
  useEffect(() => {
    axios.get("./api/getFiles").then((response) => {
      const fileDatas = response.data;
      setFiles(fileDatas);
    });
  }, []);

  // search by title
  const searchedLink = [...files].filter((data) => {
    return search.length === 0
      ? true
      : search.every((characters: string) =>
          data.title.toLowerCase().includes(characters.toLowerCase())
        );
  });

  // save selected cards
  const onSelected = (id: string) => {
    if (selectedCard.length === 0) {
      setSelectedCard([...selectedCard, id]);
      setSelectedMode(!selectedMode);
    } else {
      if (selectedCard.includes(id)) {
        setSelectedCard([...removeArrayElement(selectedCard, id)]);
      } else {
        setSelectedCard([...selectedCard, id]);
      }
    }
  };

  function removeArrayElement(array: string[], element: string): string[] {
    return array.filter((item) => item !== element);
  }

  // return unSelected mode
  const onCancel = () => {
    setSelectedMode(!selectedMode);
    setSelectedCard([]);
  };

  const abc = () => {};

  // download files
  const onDownload = (ids: string[]) => {
    console.log(ids);

    if (ids.length > 0) {
      for (const id of ids) {
        const queryParams = new URLSearchParams();
        queryParams.append("id", id);
        axios({
          method: "get",
          url: `/api/getFilesPath`,
          params: queryParams,
          responseType: "blob",
        }).then(({ data }) => {
          const downloadUrl = window.URL.createObjectURL(new Blob([data]));

          const link = document.createElement("a");

          link.href = downloadUrl;

          link.setAttribute("download", `${id}.txt`); //any other extension

          document.body.appendChild(link);

          link.click();

          link.remove();
        });
      }
    }
  };

  const onUpload = () => {
      inputFile.current.click();
  }

  return (
    <Layout home>
      <>
        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.grid_container}>
          <div className={styles.title_container}>
            {selectedMode ? (
              <div className={styles.buttonsContainer}>
                <DownloadButton
                  text="Download selected"
                  icon={DownloadIcon}
                  className={styles.download}
                  onClick={() => onDownload(selectedCard)}
                />

                <Button
                  text="Delete"
                  icon={TrashIcon}
                  className={styles.delete}
                  onClick={abc}
                />
                <Button
                  text="Cancel"
                  icon={PlusIcon}
                  className={styles.cancel}
                  onClick={onCancel}
                />
              </div>
            ) : (
              <div className={styles.buttonContainer}>
                <Button
                  text="Upload"
                  icon={DownIcon}
                  className={styles.upload}
                  onClick={onUpload}
                />
                <Button
                  text="Create"
                  icon={PlusIcon}
                  className={styles.create}
                  onClick={abc}
                />
              </div>
            )}

            <input
              type="text"
              placeholder="Search title.."
              defaultValue={search.join(" ")}
              onChange={(e) =>
                setSearch(
                  e.target.value.trim() ? e.target.value.trim().split(" ") : []
                )
              }
            />
          </div>

          <div className={styles.container_body}>
            <ul className={styles.list}>
              {searchedLink.map((file) =>
                selectedCard.includes(file.id) ? (
                  <SelectedCard
                    key={file.id}
                    {...file}
                    onClick={() => onSelected(file.id)}
                  />
                ) : (
                  <Card
                    key={file.id}
                    {...file}
                    onClick={() => onSelected(file.id)}
                  />
                )
              )}
            </ul>
          </div>
          {selectedMode && (
            <div className={styles.counter}>{selectedCard.length}</div>
          )}
          <input type="file" id="file" ref={inputFile} style={{display: 'none'}} />
        </div>
      </>
    </Layout>
  );
};

export default Home;
